import React,{useCallback,useEffect,useMemo,useState}from'react';
import{ArrowLeft,BookOpen,CalendarCheck,CheckCircle2,ClipboardCheck,FileText,GraduationCap,RefreshCw,Users,UserPlus,BarChart3,Clock,ShieldCheck}from'lucide-react';
import{useNavigate}from'react-router-dom';
import{supabase}from'../lib/supabase';

type UserStatus='pending'|'active'|'suspended'|'rejected';
interface DashboardUser{id:string;role:'admin'|'student';full_name:string;phone:string|null;student_code:string|null;status:UserStatus;created_at:string;}
interface Stats{totalStudents:number;activeStudents:number;pendingStudents:number;totalCourses:number;totalLessons:number;totalExams:number;totalSessions:number;totalVideoWatch:number;}
const statCards=[['الطلاب','إجمالي الطلاب','totalStudents',Users,'/admin/students'],['النشطون','طلاب مفعلون','activeStudents',CheckCircle2,'/admin/students'],['طلبات جديدة','تحتاج مراجعة','pendingStudents',Clock,'/admin/students'],['الكورسات','الكورسات المنشورة','totalCourses',BookOpen,'/admin/courses'],['الدروس','دروس المنصة','totalLessons',FileText,'/admin/lessons'],['الامتحانات','الاختبارات','totalExams',GraduationCap,'/admin/exams'],['جلسات الحضور','جلسات مسجلة','totalSessions',CalendarCheck,'/admin/attendance'],['مشاهدة الفيديو','إجمالي السجلات','totalVideoWatch',BarChart3,'/admin/analytics']] as const;
const quick=[['إضافة طالب','قبول وإدارة الطلاب',Users,'/admin/students'],['إدارة الكورسات','الصفوف والكورسات',BookOpen,'/admin/courses'],['إضافة درس','فيديو وPDF ومحتوى',FileText,'/admin/lessons'],['إنشاء امتحان','الأسئلة والدرجات',GraduationCap,'/admin/exams'],['الحضور','تسجيل ومراجعة الحضور',CalendarCheck,'/admin/attendance'],['المساعدون','الصلاحيات وفريق العمل',ShieldCheck,'/admin/staff']] as const;

export default function AdminDashboard(){const nav=useNavigate();const[stats,setStats]=useState<Stats>({totalStudents:0,activeStudents:0,pendingStudents:0,totalCourses:0,totalLessons:0,totalExams:0,totalSessions:0,totalVideoWatch:0});const[pending,setPending]=useState<DashboardUser[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[busyId,setBusyId]=useState<string|null>(null);const[message,setMessage]=useState('');
 const count=useCallback(async(table:string)=>{const{count,error}=await supabase.from(table).select('*',{count:'exact',head:true});if(error)return 0;return count||0},[]);
 const load=useCallback(async(silent=false)=>{silent?setRefreshing(true):setLoading(true);try{const[u,c,l,e,s,v]=await Promise.all([supabase.from('users').select('id,role,full_name,phone,student_code,status,created_at').eq('role','student').order('created_at',{ascending:false}),count('courses'),count('lessons'),count('exams'),count('attendance_sessions'),count('analytics_video_watch')]);if(u.error)throw u.error;const users=(u.data||[]) as DashboardUser[];setPending(users.filter(x=>x.status==='pending').slice(0,6));setStats({totalStudents:users.length,activeStudents:users.filter(x=>x.status==='active').length,pendingStudents:users.filter(x=>x.status==='pending').length,totalCourses:c,totalLessons:l,totalExams:e,totalSessions:s,totalVideoWatch:v});}catch(err){console.error(err);setMessage('تعذر تحميل بعض بيانات اللوحة.')}finally{setLoading(false);setRefreshing(false)}},[count]);
 useEffect(()=>{void load()},[load]);
 const updateStatus=async(id:string,status:'active'|'rejected')=>{setBusyId(id);setMessage('');try{const{error}=await supabase.from('users').update({status,is_active:status==='active',updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;setMessage(status==='active'?'تم تفعيل الطالب بنجاح':'تم رفض طلب الطالب');await load(true)}catch{setMessage('تعذر تحديث حالة الطالب')}finally{setBusyId(null)}};
 const pendingLabel=useMemo(()=>stats.pendingStudents>0?`${stats.pendingStudents.toLocaleString('ar-EG')} طلب يحتاج مراجعة`:'لا توجد طلبات معلقة',[stats.pendingStudents]);
 return <main dir="rtl" className="min-h-screen bg-[#07090f] px-3 py-4 text-white sm:px-6 sm:py-6 lg:px-8"><div className="mx-auto max-w-[1450px]">
  <header className="mb-5 rounded-[1.6rem] border border-white/[.07] bg-gradient-to-br from-[#111722] to-[#0b0f16] p-4 shadow-2xl sm:mb-7 sm:rounded-[2rem] sm:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full border border-amber-400/15 bg-amber-400/[.05] px-3 py-1.5 text-[11px] font-black text-amber-300"><ShieldCheck size={14}/>لوحة إدارة المنصة</div><h1 className="text-2xl font-black tracking-tight sm:text-4xl">مرحبًا بك أستاذ أحمد</h1><p className="mt-2 max-w-2xl text-xs leading-6 text-slate-500 sm:text-sm">من هنا تتابع الطلاب والمحتوى والاختبارات والحضور وأداء المنصة في مكان واحد.</p></div><button onClick={()=>void load(true)} disabled={refreshing} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-2xl border border-white/[.08] bg-white/[.04] px-4 text-xs font-black text-slate-300 disabled:opacity-50"><RefreshCw size={16} className={refreshing?'animate-spin':''}/>تحديث البيانات</button></div></header>
  {message&&<div className="mb-4 rounded-2xl border border-amber-400/15 bg-amber-400/[.05] p-3 text-xs font-bold text-amber-200">{message}</div>}
  {loading?<div className="rounded-3xl border border-white/[.07] bg-[#0d1118] p-14 text-center text-slate-500">جاري تجهيز لوحة الإدارة...</div>:<>
   <section className="mb-7 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-8">{statCards.map(([label,desc,key,Icon,path])=><button key={key} onClick={()=>nav(path)} className="group min-w-0 rounded-2xl border border-white/[.07] bg-[#0d1118] p-3 text-right transition hover:-translate-y-0.5 hover:border-amber-300/20 sm:rounded-3xl sm:p-4"><div className="flex items-center justify-between gap-2"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-amber-400/10 text-amber-300 sm:h-10 sm:w-10"><Icon size={18}/></span><ArrowLeft size={14} className="text-slate-700 transition group-hover:text-amber-300"/></div><p className="mt-3 text-[10px] font-bold text-slate-500 sm:text-xs">{label}</p><strong className="mt-1 block text-xl font-black sm:text-2xl">{Number(stats[key as keyof Stats]||0).toLocaleString('ar-EG')}</strong><p className="mt-1 truncate text-[9px] text-slate-600">{desc}</p></button>)}</section>
   <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]">
    <section className="rounded-[1.6rem] border border-white/[.07] bg-[#0d1118] p-4 sm:rounded-3xl sm:p-5"><div className="mb-4 flex items-center justify-between gap-3"><div><p className="text-xs font-black text-amber-300">أهم الإجراءات</p><h2 className="mt-1 text-lg font-black sm:text-xl">إدارة المنصة بسرعة</h2></div><button onClick={()=>nav('/admin/settings')} className="text-xs font-black text-slate-500 hover:text-white">الإعدادات</button></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{quick.map(([title,desc,Icon,path])=><button key={path} onClick={()=>nav(path)} className="flex min-h-28 flex-col justify-between rounded-2xl border border-white/[.06] bg-white/[.025] p-3 text-right transition hover:border-white/[.13] hover:bg-white/[.04] sm:min-h-32 sm:p-4"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-sky-400/10 text-sky-300"><Icon size={18}/></span><span><b className="block text-xs font-black sm:text-sm">{title}</b><small className="mt-1 block text-[9px] leading-4 text-slate-600 sm:text-[10px]">{desc}</small></span></button>)}</div></section>
    <section className="rounded-[1.6rem] border border-white/[.07] bg-[#0d1118] p-4 sm:rounded-3xl sm:p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-black text-amber-300">طلبات التسجيل</p><h2 className="mt-1 text-lg font-black">الطلاب الجدد</h2></div><span className="rounded-full bg-amber-400/10 px-2.5 py-1 text-[10px] font-black text-amber-300">{stats.pendingStudents}</span></div><p className="mb-4 text-[10px] text-slate-600">{pendingLabel}</p>{pending.length===0?<div className="rounded-2xl border border-dashed border-white/[.07] p-7 text-center text-xs text-slate-600">لا توجد طلبات جديدة حاليًا.</div>:<div className="space-y-2">{pending.map(student=><div key={student.id} className="rounded-2xl border border-white/[.06] bg-white/[.025] p-3"><div className="flex items-center justify-between gap-2"><div className="min-w-0"><b className="block truncate text-xs">{student.full_name}</b><span className="mt-1 block truncate text-[10px] text-slate-600">{student.student_code||student.phone||'طالب جديد'}</span></div><UserPlus size={17} className="shrink-0 text-amber-300"/></div><div className="mt-3 grid grid-cols-2 gap-2"><button disabled={busyId===student.id} onClick={()=>void updateStatus(student.id,'active')} className="rounded-xl bg-emerald-400/10 py-2 text-[10px] font-black text-emerald-300 disabled:opacity-40">قبول وتفعيل</button><button disabled={busyId===student.id} onClick={()=>void updateStatus(student.id,'rejected')} className="rounded-xl bg-red-400/10 py-2 text-[10px] font-black text-red-300 disabled:opacity-40">رفض</button></div></div>)}</div>}<button onClick={()=>nav('/admin/students')} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl border border-white/[.07] py-3 text-xs font-black text-slate-400 hover:text-white">عرض كل الطلاب<ArrowLeft size={14}/></button></section>
   </div>
  </>}
 </div></main>
}
