import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Camera, Check, Search, X } from 'lucide-react';
import { supabase } from '../lib/supabase';

type Row = Record<string, any>;
export default function AttendanceAdminPage(){
 const [sessions,setSessions]=useState<Row[]>([]),[groups,setGroups]=useState<Row[]>([]),[students,setStudents]=useState<Row[]>([]),[sessionId,setSessionId]=useState(''),[code,setCode]=useState(''),[status,setStatus]=useState('present'),[search,setSearch]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[camera,setCamera]=useState(false),[scanning,setScanning]=useState(false);const videoRef=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);
 const load=useCallback(async()=>{const [s,g,st]=await Promise.all([supabase.from('sessions').select('id,session_date,start_time,end_time,group_id,status').order('session_date',{ascending:false}).limit(100),supabase.from('groups').select('id,name').eq('is_active',true),supabase.from('students').select('user_id,group_id,profiles!students_user_id_fkey(full_name,phone),student_profiles!students_user_id_fkey(student_code)').limit(500)]);if(s.error||g.error||st.error){setError('تعذر تحميل بيانات الحضور.');return;}setSessions(s.data??[]);setGroups(g.data??[]);setStudents(st.data??[]);},[]);
 useEffect(()=>{void load();return()=>stopCamera()},[load]);
 const stopCamera=()=>{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setCamera(false);setScanning(false)};
 const mark=async(studentCode:string)=>{setError('');setMessage('');if(!sessionId)return setError('اختر جلسة الحضور أولًا.');if(!studentCode.trim())return setError('أدخل كود الطالب.');const {data,error:e}=await supabase.rpc('mark_attendance_by_student_code',{p_session_id:sessionId,p_student_code:studentCode.trim(),p_status:status});if(e){console.error(e);setError('تعذر تسجيل الحضور. تأكد من الجلسة والكود.');return;}setMessage(`تم تسجيل ${data?.full_name??'الطالب'}: ${status==='present'?'حاضر':status==='late'?'متأخر':status==='absent'?'غائب':'بعذر'}`);setCode('');};
 const startCamera=async()=>{setError('');try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});streamRef.current=stream;if(videoRef.current)videoRef.current.srcObject=stream;setCamera(true);setScanning(true);}catch(e){console.error(e);setError('تعذر فتح الكاميرا. استخدم البحث أو التسجيل اليدوي.')}};
 useEffect(()=>{if(!scanning)return;const Detector=(window as any).BarcodeDetector;if(!Detector){setError('قارئ QR غير مدعوم في هذا المتصفح. استخدم التسجيل اليدوي.');return;}const detector=new Detector({formats:['qr_code']});let stopped=false;const loop=async()=>{if(stopped||!videoRef.current)return;try{const codes=await detector.detect(videoRef.current);const value=codes?.[0]?.rawValue;if(value){stopped=true;stopCamera();await mark(value)}}catch(e){console.error(e)}if(!stopped)requestAnimationFrame(loop)};const timer=window.setTimeout(()=>void loop(),500);return()=>{stopped=true;window.clearTimeout(timer)}},[scanning]);
 const filtered=students.filter(s=>{const p=Array.isArray(s.profiles)?s.profiles[0]:s.profiles;const sp=Array.isArray(s.student_profiles)?s.student_profiles[0]:s.student_profiles;const q=search.trim().toLowerCase();return !q||String(p?.full_name??'').toLowerCase().includes(q)||String(p?.phone??'').includes(q)||String(sp?.student_code??'').toLowerCase().includes(q)});
 return <main dir="rtl" className="min-h-screen bg-[#07090f] px-4 py-6 text-white sm:px-6"><div className="mx-auto max-w-6xl"><header className="mb-7"><p className="text-xs font-black text-sky-400">الحضور</p><h1 className="mt-2 text-3xl font-black">تسجيل الحضور</h1><p className="mt-2 text-sm text-slate-500">ابحث بالاسم أو رقم الهاتف أو كود الطالب، أو امسح كود الطالب بالكاميرا.</p></header>{error&&<div className="mb-4 rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm font-bold text-red-300">{error}</div>}{message&&<div className="mb-4 rounded-2xl border border-emerald-400/20 bg-emerald-400/10 p-4 text-sm font-bold text-emerald-300">{message}</div>}
 <section className="mb-5 grid gap-3 lg:grid-cols-3"><label className="text-xs font-black text-slate-400">جلسة الحضور<select className="mt-2 w-full rounded-2xl border border-white/[0.08] bg-[#11151d] px-4 py-3 text-white" value={sessionId} onChange={e=>setSessionId(e.target.value)}><option value="">اختر الجلسة</option>{sessions.map(x=><option key={x.id} value={x.id}>{x.session_date} • {groups.find(g=>g.id===x.group_id)?.name??'مجموعة'}</option>)}</select></label><label className="text-xs font-black text-slate-400">الحالة<select className="mt-2 w-full rounded-2xl border border-white/[0.08] bg-[#11151d] px-4 py-3 text-white" value={status} onChange={e=>setStatus(e.target.value)}><option value="present">حاضر</option><option value="late">متأخر</option><option value="absent">غائب</option><option value="excused">بعذر</option></select></label><div className="flex items-end"><button type="button" onClick={()=>camera?stopCamera():void startCamera()} className="w-full rounded-2xl bg-sky-500 px-4 py-3 font-black text-slate-950">{camera?<><X size={17} className="inline"/> إغلاق الكاميرا</>:<><Camera size={17} className="inline"/> مسح QR</>}</button></div></section>
 {camera&&<div className="mb-5 rounded-3xl border border-white/[0.07] bg-[#0d1118] p-4"><video ref={videoRef} autoPlay playsInline className="mx-auto max-h-80 rounded-2xl"/><p className="mt-3 text-center text-xs text-slate-500">وجّه الكاميرا إلى QR الخاص بكود الطالب.</p></div>}
 <section className="mb-5 rounded-3xl border border-white/[0.07] bg-[#0d1118] p-5"><div className="flex gap-2"><input className="w-full rounded-2xl border border-white/[0.08] bg-[#11151d] px-4 py-3 text-white" value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void mark(code)}} placeholder="اكتب كود الطالب ثم Enter"/><button type="button" onClick={()=>void mark(code)} className="rounded-2xl bg-emerald-500 px-5 font-black text-slate-950"><Check size={18}/></button></div></section>
 <section className="rounded-3xl border border-white/[0.07] bg-[#0d1118] p-5"><div className="mb-4 flex items-center gap-3"><Search size={18} className="text-sky-400"/><input className="w-full rounded-2xl border border-white/[0.08] bg-[#11151d] px-4 py-3 text-white" value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث بالاسم / رقم الهاتف / كود الطالب"/><span className="whitespace-nowrap text-xs font-black text-slate-500">{filtered.length} نتيجة</span></div><div className="grid gap-2">{filtered.slice(0,50).map(s=>{const p=Array.isArray(s.profiles)?s.profiles[0]:s.profiles;const sp=Array.isArray(s.student_profiles)?s.student_profiles[0]:s.student_profiles;return <div key={s.user_id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-white/[0.03] p-4"><div><div className="font-black">{p?.full_name||'بدون اسم'}</div><div className="mt-1 text-xs text-slate-500">الهاتف: {p?.phone||'—'} • الكود: {sp?.student_code||'—'}</div></div><button type="button" disabled={!sp?.student_code} onClick={()=>void mark(sp.student_code)} className="rounded-xl bg-white/[0.06] px-4 py-2 text-xs font-black disabled:opacity-30">تسجيل حضور</button></div>})}{filtered.length===0&&<div className="py-10 text-center text-sm text-slate-500">لا توجد نتائج مطابقة.</div>}</div></section></div></main>;
}
