import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Award, Brain, CheckCircle2, ChevronLeft, ClipboardCheck, FlaskConical, GraduationCap, LogIn, Menu, Moon, PlayCircle, ShieldCheck, Sparkles, Sun, Target, Users, X } from 'lucide-react';
import { useAuthStore } from '../store/authStore';

const features = [
  { icon: PlayCircle, title: 'شرح واضح ومنظم', text: 'محتوى مرتب يساعدك تمشي في المنهج خطوة بخطوة من غير تشتت.' },
  { icon: ClipboardCheck, title: 'تدريب واختبارات', text: 'حل أسئلة وقيّم مستواك باستمرار، واعرف أين تحتاج إلى مزيد من التدريب.' },
  { icon: Target, title: 'تركيز على الفهم', text: 'نحوّل القاعدة والمعلومة إلى فهم وتطبيق، بدل الاعتماد على الحفظ وحده.' },
  { icon: ShieldCheck, title: 'متابعة منظمة', text: 'بيئة تعليمية تجمع المحتوى والتدريب والدرجات والمتابعة في مكان واحد.' },
];
const benefits = ['تفهم الفكرة قبل أن تبدأ في حفظها.','تتدرّب على أنماط مختلفة من الأسئلة.','تكتشف أخطاءك وتعرف كيف تتجنب تكرارها.','تراجع الدروس في الوقت الذي يناسبك.','تتابع مستواك بصورة أوضح مع الوقت.','تبني ثقة حقيقية في قدرتك على حل السؤال.'];
const grades = [
  ['01', 'الصف الأول الثانوي', 'بداية قوية وفهم سليم لأساسيات الكيمياء.', 'first'],
  ['02', 'الصف الثاني الثانوي', 'تعمّق أكبر في المفاهيم والتطبيق وحل الأسئلة.', 'second'],
  ['03', 'الصف الثالث الثانوي', 'مراجعة وتدريب مكثف والاستعداد الجاد للامتحان.', 'third'],
];
function initialTheme(): 'dark' | 'light' { const saved = localStorage.getItem('platform-theme'); if (saved === 'light' || saved === 'dark') return saved; return window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark'; }

export default function HomePage() {
  const { user } = useAuthStore();
  const [theme, setTheme] = useState<'dark' | 'light'>(() => initialTheme());
  const [menuOpen, setMenuOpen] = useState(false);
  const [teacherImageError, setTeacherImageError] = useState(false);
  const light = theme === 'light';
  const dashboardHref = user ? '/dashboard' : '/auth';
  useEffect(() => { document.documentElement.dataset.theme = theme; document.documentElement.style.colorScheme = theme; localStorage.setItem('platform-theme', theme); }, [theme]);
  const closeMenu = () => setMenuOpen(false);
  return (
    <main dir="rtl" className={`home-page min-h-screen overflow-x-hidden ${light ? 'home-light' : 'home-dark'}`}>
      <header className={`home-header sticky top-0 z-50 border-b backdrop-blur-2xl ${light ? 'border-slate-200/80 bg-white/85' : 'border-white/[0.07] bg-[#06080d]/85'}`}>
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-3 sm:px-6 lg:px-8">
          <Link to="/" className="brand flex min-w-0 items-center gap-3"><div className="brand-mark flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl text-xl font-black">أ</div><div className="min-w-0"><p className="truncate text-sm font-black sm:text-base">منصة أ. أحمد محمد رمضان</p><p className="text-[11px] opacity-60">منصة الكيمياء التعليمية</p></div></Link>
          <nav className="hidden items-center gap-7 md:flex"><a href="#about" className="nav-link text-sm font-bold">عن المستر</a><a href="#experience" className="nav-link text-sm font-bold">ماذا ستستفيد؟</a><a href="#features" className="nav-link text-sm font-bold">مميزات المنصة</a><a href="#updates" className="nav-link text-sm font-bold">أحدث المستجدات</a></nav>
          <div className="flex items-center gap-2"><button type="button" onClick={() => setTheme(light ? 'dark' : 'light')} aria-label="تغيير الوضع" className="theme-button flex h-10 w-10 items-center justify-center rounded-xl border">{light ? <Moon className="h-4 w-4" /> : <Sun className="h-4 w-4" />}</button><Link to={dashboardHref} className="gold-button inline-flex min-h-10 items-center gap-2 rounded-xl px-3 text-xs font-black sm:px-4 sm:text-sm"><LogIn className="h-4 w-4" />{user ? 'لوحتي' : 'تسجيل الدخول'}</Link><button type="button" onClick={() => setMenuOpen(v => !v)} aria-label="القائمة" className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/10 md:hidden">{menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>
        </div>
        {menuOpen && <div className={`mobile-menu border-t px-4 py-3 md:hidden ${light ? 'border-slate-200 bg-white' : 'border-white/[0.06] bg-[#0a0d14]'}`}><div className="grid gap-1"><a onClick={closeMenu} href="#about" className="rounded-xl px-3 py-3 text-sm font-bold">عن المستر</a><a onClick={closeMenu} href="#experience" className="rounded-xl px-3 py-3 text-sm font-bold">ماذا ستستفيد؟</a><a onClick={closeMenu} href="#features" className="rounded-xl px-3 py-3 text-sm font-bold">مميزات المنصة</a><a onClick={closeMenu} href="#updates" className="rounded-xl px-3 py-3 text-sm font-bold">أحدث المستجدات</a></div></div>}
      </header>

      <section className="hero relative overflow-hidden"><div className="hero-orb hero-orb-one"/><div className="hero-orb hero-orb-two"/><div className="hero-grid"/><div className="relative mx-auto grid max-w-7xl items-center gap-12 px-4 pb-16 pt-12 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pb-24 lg:pt-20">
        <div className="hero-copy"><div className="hero-badge mb-5 inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-black"><Sparkles className="h-4 w-4"/>تعلم الكيمياء بفهم وثقة</div><h1 className="hero-title max-w-3xl text-4xl font-black leading-[1.18] tracking-tight sm:text-5xl lg:text-6xl">مش هدفنا تحفظ الكيمياء…<span className="mt-2 block">هدفنا إنك تفهمها.</span></h1><p className="hero-subtitle mt-6 max-w-2xl text-base leading-8 sm:text-lg">مع أستاذ أحمد محمد رمضان، تتعلم الكيمياء خطوة بخطوة، وتحوّل المعلومة إلى فهم وتطبيق وحل أسئلة، في تجربة تعليمية منظمة تناسب طالب المرحلة الثانوية.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to={dashboardHref} className="gold-button magnetic-button inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl px-7 text-sm font-black">{user ? 'فتح لوحتي' : 'ابدأ رحلتك التعليمية'}<ArrowLeft className="h-4 w-4"/></Link>{!user && <Link to="/auth?mode=register" className="secondary-button inline-flex min-h-12 items-center justify-center rounded-2xl border px-7 text-sm font-bold">إنشاء حساب طالب</Link>}</div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-xs font-bold opacity-65"><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-500"/>شرح منظم</span><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-500"/>تدريب مستمر</span><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-500"/>متابعة للمستوى</span></div></div>
        <div className="hero-visual relative mx-auto w-full max-w-[440px]"><div className="hero-image-glow absolute inset-8 rounded-[3rem] blur-3xl"/><div className="hero-image-card relative overflow-hidden rounded-[2.25rem] border p-3 shadow-2xl"><div className="hero-image-wrap relative aspect-[4/5] overflow-hidden rounded-[1.8rem] bg-slate-900">{!teacherImageError ? <img src="/teacher-ahmed.jpg" alt="أستاذ أحمد محمد رمضان" className="teacher-image h-full w-full object-cover" onError={() => setTeacherImageError(true)}/> : <div className="flex h-full items-center justify-center"><div className="text-center"><div className="mx-auto flex h-36 w-36 items-center justify-center rounded-full border-4 border-amber-300/30 bg-black/25 text-7xl font-black text-amber-300">أ</div><p className="mt-6 text-2xl font-black text-white">أ. أحمد محمد رمضان</p></div></div>}<div className="image-shine"/><div className="absolute inset-x-4 bottom-4 rounded-2xl border border-white/10 bg-black/55 p-4 backdrop-blur-xl"><div className="flex items-center justify-between gap-3"><div><p className="text-base font-black text-white">أ. أحمد محمد رمضان</p><p className="mt-1 text-xs text-slate-300">مدرس الكيمياء للمرحلة الثانوية</p></div><div className="float-icon flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-amber-400 text-black"><FlaskConical className="h-5 w-5"/></div></div></div></div></div><div className="floating-chip floating-chip-one"><CheckCircle2 className="h-4 w-4"/>فهم قبل الحفظ</div><div className="floating-chip floating-chip-two"><FlaskConical className="h-4 w-4"/>كيمياء ببساطة</div></div>
      </div></section>

      <section id="about" className="section-reveal border-y"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[.78fr_1.22fr] lg:px-8"><div><p className="eyebrow text-sm font-black">عن المستر</p><h2 className="section-title mt-3 text-3xl font-black leading-tight sm:text-4xl">مدرس هدفه إن المعلومة توصل للطالب فعلًا.</h2><div className="mt-6 flex items-center gap-3"><div className="icon-box flex h-11 w-11 items-center justify-center rounded-2xl"><Award className="h-5 w-5"/></div><div><p className="text-sm font-black">تعليم قائم على الفهم والتطبيق</p><p className="mt-1 text-xs opacity-50">مش مجرد حفظ للإجابة</p></div></div></div><div className="section-copy space-y-5 text-sm leading-8 sm:text-base"><p>أستاذ أحمد محمد رمضان يهتم بأن يفهم الطالب الفكرة من أساسها، ويعرف كيف يستخدمها في السؤال، بدل ما يعتمد على حفظ خطوات ثابتة قد لا تنفعه عندما يتغير شكل السؤال.</p><p>الشرح يبدأ من تبسيط المفهوم، ثم ربطه بما سبقه، وبعدها الانتقال إلى التطبيق والتدريب؛ لأن الفهم الحقيقي يظهر عندما يستطيع الطالب أن يفكر ويحل بنفسه.</p><p className="font-bold text-amber-500">الهدف في النهاية ليس أن تعرف الإجابة فقط، ولكن أن تعرف كيف وصلت إليها.</p></div></div></section>

      <section id="experience" className="section-reveal mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow text-sm font-black">إيه اللي هتستفيده؟</p><h2 className="section-title mt-3 text-3xl font-black leading-tight sm:text-4xl">هتذاكر بشكل أهدى… وتحس بتقدمك بشكل أوضح.</h2><p className="section-copy mt-5 text-sm leading-8">التعلم الجيد مش بكثرة الساعات، لكن بجودة الفهم والتدريب ومعرفة نقاط الضعف والعمل عليها.</p></div><div className="grid gap-3 sm:grid-cols-2">{benefits.map((benefit,index)=><div key={benefit} className="benefit-card flex gap-3 rounded-2xl border p-4"><div className="benefit-number flex h-7 w-7 shrink-0 items-center justify-center rounded-lg text-xs font-black">{index+1}</div><p className="text-sm font-bold leading-6">{benefit}</p></div>)}</div></div></section>

      <section id="features" className="section-reveal features-section border-y"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="mb-9 text-center"><p className="eyebrow text-sm font-black">التجربة التعليمية</p><h2 className="section-title mt-2 text-3xl font-black">كل اللي تحتاجه في مكان واحد</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(({icon:Icon,title,text})=><div key={title} className="feature-card rounded-3xl border p-5"><div className="feature-icon flex h-12 w-12 items-center justify-center rounded-2xl"><Icon className="h-5 w-5"/></div><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-7 opacity-55">{text}</p></div>)}</div></div></section>

      <section className="section-reveal mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="mb-9 text-center"><p className="eyebrow text-sm font-black">طلابنا</p><h2 className="section-title mt-2 text-3xl font-black">رحلتك تبدأ من صفك</h2></div><div className="grid gap-4 md:grid-cols-3">{grades.map(([number,title,text,grade])=><Link key={number} to={`/auth?mode=register&grade=${grade}`} className="grade-card group rounded-3xl border p-6"><div className="flex items-center justify-between"><span className="grade-number text-4xl font-black">{number}</span><GraduationCap className="h-6 w-6 text-amber-500"/></div><h3 className="mt-7 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-7 opacity-55">{text}</p><div className="mt-5 inline-flex items-center gap-1 text-xs font-black text-amber-500">سجل وابدأ <ChevronLeft className="h-4 w-4 transition group-hover:-translate-x-1"/></div></Link>)}</div></section>

      <section id="updates" className="section-reveal updates-section border-y"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><div className="update-badge mb-4 inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-black"><Brain className="h-4 w-4"/>معاك في كل جديد</div><h2 className="section-title text-3xl font-black leading-tight sm:text-4xl">التعليم بيتطور… وإحنا بنتابع.</h2></div><div className="update-card rounded-3xl border p-6"><div className="flex gap-4"><div className="feature-icon flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl"><Sparkles className="h-5 w-5"/></div><div><h3 className="font-black">مواكبة أحدث المستجدات التعليمية</h3><p className="section-copy mt-2 text-sm leading-8">مع التحديثات المستمرة في نظم الدراسة والمناهج والتقييم، نحرص على أن تظل المنصة مواكبة لكل جديد يهم الطالب وولي الأمر.</p></div></div></div></div></div></section>

      <section className="section-reveal mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="cta-card relative overflow-hidden rounded-[2rem] border p-7 text-center sm:p-10"><div className="cta-orb"/><Users className="relative mx-auto h-9 w-9 text-amber-400"/><h2 className="relative mt-4 text-3xl font-black">ابدأ من النهارده</h2><p className="section-copy relative mx-auto mt-3 max-w-2xl text-sm leading-7">خلّي مذاكرة الكيمياء أكثر تنظيمًا، وابدأ تبني فهمك خطوة بخطوة.</p><Link to={dashboardHref} className="gold-button magnetic-button relative mt-6 inline-flex min-h-12 items-center gap-2 rounded-2xl px-7 text-sm font-black">{user ? 'الذهاب إلى لوحتي' : 'ابدأ التعلم الآن'}<ArrowLeft className="h-4 w-4"/></Link></div></section>

      <footer className="home-footer border-t"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-8 sm:px-6 md:flex-row md:items-center md:justify-between lg:px-8"><div><p className="font-black">منصة أ. أحمد محمد رمضان</p><p className="mt-1 text-xs opacity-50">تعلم الكيمياء بفهم وثقة.</p></div><div className="flex flex-wrap gap-4 text-xs font-bold opacity-50"><Link to="/auth" className="hover:text-amber-500">تسجيل الدخول</Link><a href="#about" className="hover:text-amber-500">عن المستر</a><a href="#features" className="hover:text-amber-500">مميزات المنصة</a></div><p className="text-xs opacity-50">© {new Date().getFullYear()} جميع الحقوق محفوظة.</p></div></footer>
    </main>
  );
}
