import React,{useEffect,useMemo,useState}from'react';
import{useNavigate,useParams}from'react-router-dom';
import{AlertCircle,CheckCircle2,Clock,Loader2,Send,ShieldCheck}from'lucide-react';
import{supabase}from'../lib/supabase';

type Choice={id:string;choice_text:string;display_order:number};
type Question={id:string;question_text:string;question_type:'multiple_choice'|'true_false'|'short_answer';points:number;display_order:number;choices:Choice[]};
type Answer={selected_choice_id?:string;answer_text?:string};

export default function StudentExamPage(){
 const{examId}=useParams();const navigate=useNavigate();
 const[loading,setLoading]=useState(true);const[questions,setQuestions]=useState<Question[]>([]);const[answers,setAnswers]=useState<Record<string,Answer>>({});const[error,setError]=useState('');const[submitting,setSubmitting]=useState(false);const[result,setResult]=useState<{score:number;max_score:number;reason:string}|null>(null);
 useEffect(()=>{let alive=true;(async()=>{if(!examId){setError('الامتحان غير صحيح.');setLoading(false);return}setLoading(true);setError('');const{data:claim,error:claimError}=await supabase.rpc('claim_exam_access',{p_exam_id:examId});const row=Array.isArray(claim)?claim[0]:claim;if(claimError||!row?.allowed){setError(claimError?'تعذر فتح الامتحان.':row?.reason||'لا يمكن فتح الامتحان.');setLoading(false);return}const{data:q,error:qError}=await supabase.rpc('get_student_exam_questions',{p_exam_id:examId});if(alive){if(qError)setError('تعذر تحميل أسئلة الامتحان.');else setQuestions((q||[]) as Question[]);setLoading(false)}})();return()=>{alive=false}},[examId]);
 const total=useMemo(()=>questions.reduce((s,q)=>s+Number(q.points||0),0),[questions]);
 const setChoice=(qid:string,id:string)=>setAnswers(a=>({...a,[qid]:{selected_choice_id:id}}));
 const setText=(qid:string,text:string)=>setAnswers(a=>({...a,[qid]:{answer_text:text}}));
 async function submit(){if(!examId||submitting)return;setSubmitting(true);setError('');const payload=questions.map(q=>({question_id:q.id,selected_choice_id:answers[q.id]?.selected_choice_id||null,answer_text:answers[q.id]?.answer_text||null}));const{data,error:e}=await supabase.rpc('submit_student_exam',{p_exam_id:examId,p_answers:payload});const row=Array.isArray(data)?data[0]:data;if(e||!row?.submitted){setError(e?'تعذر تسليم الامتحان.':row?.reason||'تعذر التسليم.');setSubmitting(false);return}setResult({score:Number(row.score||0),max_score:Number(row.max_score||total),reason:row.reason});setSubmitting(false)}
 if(loading)return <main dir="rtl" className="min-h-screen bg-[#07090f] p-4 text-white grid place-items-center"><div className="text-center"><Loader2 className="mx-auto mb-3 animate-spin text-amber-300"/><p className="text-slate-400">جاري تأمين وفتح الامتحان...</p></div></main>;
 if(result)return <main dir="rtl" className="min-h-screen bg-[#07090f] p-4 text-white sm:p-8"><div className="mx-auto max-w-2xl rounded-[2rem] border border-emerald-400/10 bg-[#0d1118] p-6 text-center sm:p-10"><CheckCircle2 className="mx-auto mb-4 text-emerald-300" size={48}/><h1 className="text-2xl font-black">تم تسليم الامتحان</h1><p className="mt-3 text-slate-400">{result.reason}</p><div className="mx-auto mt-7 flex max-w-sm items-center justify-center gap-5 rounded-3xl bg-white/[.04] p-6"><div><p className="text-xs text-slate-500">درجتك</p><strong className="text-4xl">{result.score}</strong></div><span className="text-slate-600">/</span><div><p className="text-xs text-slate-500">من</p><strong className="text-2xl">{result.max_score}</strong></div></div><button onClick={()=>navigate('/dashboard/exams')} className="mt-7 min-h-11 rounded-2xl bg-amber-300 px-6 font-black text-black">العودة للامتحانات</button></div></main>;
 if(error)return <main dir="rtl" className="min-h-screen bg-[#07090f] p-4 text-white sm:p-8"><div className="mx-auto max-w-2xl rounded-[2rem] border border-red-400/10 bg-[#0d1118] p-7 text-center"><AlertCircle className="mx-auto mb-4 text-red-300" size={42}/><h1 className="text-xl font-black">تعذر فتح الامتحان</h1><p className="mt-3 leading-7 text-slate-400">{error}</p><button onClick={()=>navigate('/dashboard/exams')} className="mt-6 min-h-11 rounded-2xl border border-white/10 px-5 font-black">العودة</button></div></main>;
 return <main dir="rtl" className="min-h-screen bg-[#07090f] px-3 py-4 text-white sm:px-6 sm:py-8"><div className="mx-auto max-w-4xl"><header className="mb-5 rounded-[2rem] border border-white/[.07] bg-[#0d1118] p-5 sm:p-7"><div className="flex items-start gap-3"><ShieldCheck className="mt-1 shrink-0 text-emerald-300"/><div><h1 className="text-2xl font-black">الامتحان</h1><p className="mt-2 text-sm leading-6 text-slate-400">الأسئلة يتم تحميلها من الخادم بدون إظهار الإجابات الصحيحة للمتصفح.</p><div className="mt-3 flex items-center gap-2 text-xs font-black text-amber-300"><Clock size={15}/>{questions.length} سؤال • {total} درجة</div></div></div></header><div className="space-y-4">{questions.map((q,i)=><article key={q.id} className="rounded-[1.75rem] border border-white/[.07] bg-[#0d1118] p-5 sm:p-6"><div className="mb-4 flex items-start justify-between gap-3"><h2 className="font-black leading-7">{i+1}. {q.question_text}</h2><span className="shrink-0 rounded-full bg-violet-400/10 px-3 py-1 text-[11px] font-black text-violet-300">{q.points} درجة</span></div>{q.question_type==='short_answer'?<textarea value={answers[q.id]?.answer_text||''} onChange={e=>setText(q.id,e.target.value)} className="min-h-28 w-full rounded-2xl border border-white/10 bg-black/20 p-4 text-sm outline-none focus:border-violet-400/40" placeholder="اكتب إجابتك..."/>:<div className="grid gap-2">{q.choices.map(c=><label key={c.id} className="flex cursor-pointer items-center gap-3 rounded-2xl border border-white/[.06] bg-white/[.02] p-4 hover:bg-white/[.04]"><input type="radio" name={q.id} checked={answers[q.id]?.selected_choice_id===c.id} onChange={()=>setChoice(q.id,c.id)} className="h-4 w-4"/><span className="text-sm font-bold">{c.choice_text}</span></label>)}</div>}</article>)}</div>{error&&<p className="mt-4 rounded-2xl bg-red-400/10 p-4 text-sm font-bold text-red-300">{error}</p>}<button disabled={submitting||questions.length===0} onClick={submit} className="sticky bottom-3 mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-amber-300 px-6 font-black text-black disabled:cursor-not-allowed disabled:opacity-50">{submitting?<><Loader2 className="animate-spin" size={18}/>جاري التسليم...</>:<><Send size={18}/>تسليم الامتحان نهائيًا</>}</button></div></main>
}
