import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Camera, CheckCircle2, X } from 'lucide-react';
import { supabase } from '../lib/supabase';

export default function StudentAttendancePage(){
 const [records,setRecords]=useState<any[]>([]),[token,setToken]=useState(''),[camera,setCamera]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');const videoRef=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);
 const load=useCallback(async()=>{const{data,error:e}=await supabase.from('attendance').select('id,status,marked_at,session_id,sessions(session_date,start_time,end_time)').order('marked_at',{ascending:false}).limit(30);if(e){setError('تعذر تحميل سجل الحضور.');return}setRecords(data??[])},[]);
 useEffect(()=>{void load();return()=>stop()},[load]);
 const stop=()=>{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setCamera(false)};
 const checkIn=async(value:string)=>{setError('');setMessage('');if(!value.trim())return setError('امسح QR الحضور أو أدخل الكود.');const{data,error:e}=await supabase.rpc('student_check_in_attendance',{p_token:value.trim()});if(e){console.error(e);setError('تعذر تسجيل الحضور. تأكد أن الجلسة مفتوحة وأن QR صحيح.');return}setMessage(data?.message||'تم تسجيل حضورك بنجاح.');setToken('');await load()};
 const start=async()=>{setError('');try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});streamRef.current=stream;if(videoRef.current)videoRef.current.srcObject=stream;setCamera(true);const Detector=(window as any).BarcodeDetector;if(!Detector){setError('قارئ QR غير مدعوم. استخدم إدخال الكود اليدوي.');return}const detector=new Detector({formats:['qr_code']});let active=true;const scan=async()=>{if(!active||!videoRef.current)return;try{const found=await detector.detect(videoRef.current);if(found?.[0]?.rawValue){active=false;stop();await checkIn(found[0].rawValue);return}}catch(e){console.error(e)}requestAnimationFrame(scan)};setTimeout(()=>void scan(),500)}catch(e){console.error(e);setError('تعذر فتح الكاميرا. اسمح بالوصول للكاميرا أو استخدم الكود اليدوي.')}};
 return <main dir="rtl" className="min-h-screen bg-[#07090f] px-4 py-6 text-white sm:px-6"><div className="mx-auto max-w-4xl"><header className="mb-7"><p className="text-xs font-black text-sky-400">الطالب</p><h1 className="mt-2 text-3xl font-black">تسجيل الحضور</h1><p className="mt-2 text-sm text-slate-500">امسح QR الذي يعرضه المدرس أثناء الجلسة، أو استخدم كود الحضور اليدوي.</p></header>{error&&<div className="mb-4 rounded-2xl border border-red-400/20 bg-red-400/10 p-4 font-bold text-red-300">{error}</div>}{message&&<div className="mb-4 flex items-center gap-2 rounded-2xl border border-emerald-400/20 bg-emerald-400/10 p-4 font-bold text-emerald-300"><CheckCircle2 size={18}/>{message}</div>}
 <section className="mb-5 rounded-3xl border border-white/[0.07] bg-[#0d1118] p-5"><button type="button" onClick={()=>camera?stop():void start()} className="mb-4 w-full rounded-2xl bg-sky-500 px-5 py-3 font-black text-slate-950">{camera?<><X size={17} className="inline"/> إغلاق الكاميرا</>:<><Camera size={17} className="inline"/> مسح QR</>}</button>{camera&&<video ref={videoRef} autoPlay playsInline className="mx-auto max-h-80 rounded-2xl"/>}<div className="mt-4 flex gap-2"><input className="w-full rounded-2xl border border-white/[0.08] bg-[#11151d] px-4 py-3 text-white" value={token} onChange={e=>setToken(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void checkIn(token)}} placeholder="كود الحضور"/><button type="button" onClick={()=>void checkIn(token)} className="rounded-2xl bg-emerald-500 px-5 font-black text-slate-950">تسجيل</button></div></section>
 <section className="rounded-3xl border border-white/[0.07] bg-[#0d1118] p-5"><h2 className="mb-4 font-black">سجل حضورك</h2><div className="grid gap-2">{records.map(r=><div key={r.id} className="flex items-center justify-between rounded-2xl bg-white/[0.03] p-4"><div><b>{r.sessions?.session_date||'جلسة'}</b><p className="mt-1 text-xs text-slate-500">{r.marked_at?new Date(r.marked_at).toLocaleString('ar-EG'):''}</p></div><span className="rounded-xl bg-emerald-400/10 px-3 py-2 text-xs font-black text-emerald-300">{r.status}</span></div>)}{records.length===0&&<div className="py-10 text-center text-sm text-slate-500">لا يوجد سجل حضور بعد.</div>}</div></section></div></main>;
}
