-- =========================================================
-- منصة أستاذ أحمد محمد رمضان
-- Analytics System
-- =========================================================

-- =========================================================
-- 1. Analytics Events
-- =========================================================

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,

  user_id uuid references public.users(id) on delete cascade,

  event_type text not null,

  page_path text,
  content_id uuid,
  content_type text,

  metadata jsonb not null default '{}'::jsonb,

  session_id uuid,

  created_at timestamptz not null default now()
);


-- =========================================================
-- 2. Student Sessions
-- =========================================================

create table if not exists public.analytics_sessions (
  id uuid primary key default gen_random_uuid(),

  user_id uuid not null
    references public.users(id)
    on delete cascade,

  started_at timestamptz not null default now(),

  last_seen_at timestamptz not null default now(),

  ended_at timestamptz,

  duration_seconds integer not null default 0,

  is_online boolean not null default true,

  device_type text,

  browser text,

  operating_system text,

  ip_hash text,

  created_at timestamptz not null default now()
);


-- =========================================================
-- 3. Video Watching
-- =========================================================

create table if not exists public.analytics_video_watch (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references public.users(id)
    on delete cascade,

  video_id uuid not null,

  session_id uuid
    references public.analytics_sessions(id)
    on delete set null,

  watched_seconds integer not null default 0,

  video_duration_seconds integer not null default 0,

  watch_percentage numeric(5,2)
    generated always as (
      case
        when video_duration_seconds > 0
        then round(
          (watched_seconds::numeric / video_duration_seconds::numeric) * 100,
          2
        )
        else 0
      end
    ) stored,

  play_count integer not null default 0,

  pause_count integer not null default 0,

  completed boolean not null default false,

  first_started_at timestamptz,

  last_watched_at timestamptz not null default now(),

  created_at timestamptz not null default now(),

  unique(user_id, video_id)
);


-- =========================================================
-- 4. Indexes
-- =========================================================

create index if not exists idx_analytics_events_user
on public.analytics_events(user_id);

create index if not exists idx_analytics_events_created
on public.analytics_events(created_at desc);

create index if not exists idx_analytics_events_type
on public.analytics_events(event_type);

create index if not exists idx_analytics_sessions_user
on public.analytics_sessions(user_id);

create index if not exists idx_analytics_sessions_online
on public.analytics_sessions(is_online);

create index if not exists idx_analytics_sessions_last_seen
on public.analytics_sessions(last_seen_at desc);

create index if not exists idx_video_watch_user
on public.analytics_video_watch(user_id);

create index if not exists idx_video_watch_video
on public.analytics_video_watch(video_id);


-- =========================================================
-- 5. RLS
-- =========================================================

alter table public.analytics_events enable row level security;

alter table public.analytics_sessions enable row level security;

alter table public.analytics_video_watch enable row level security;


-- =========================================================
-- 6. Student Policies
-- =========================================================

create policy "students_insert_own_events"
on public.analytics_events
for insert
to authenticated
with check (
  auth.uid() = user_id
);


create policy "students_read_own_events"
on public.analytics_events
for select
to authenticated
using (
  auth.uid() = user_id
);


create policy "students_manage_own_sessions"
on public.analytics_sessions
for all
to authenticated
using (
  auth.uid() = user_id
)
with check (
  auth.uid() = user_id
);


create policy "students_manage_own_video_watch"
on public.analytics_video_watch
for all
to authenticated
using (
  auth.uid() = user_id
)
with check (
  auth.uid() = user_id
);


-- =========================================================
-- 7. Admin Policies
-- =========================================================

create policy "admins_read_all_events"
on public.analytics_events
for select
to authenticated
using (
  exists (
    select 1
    from public.users
    where users.id = auth.uid()
      and users.role = 'admin'
      and users.status = 'active'
  )
);


create policy "admins_read_all_sessions"
on public.analytics_sessions
for select
to authenticated
using (
  exists (
    select 1
    from public.users
    where users.id = auth.uid()
      and users.role = 'admin'
      and users.status = 'active'
  )
);


create policy "admins_read_all_video_watch"
on public.analytics_video_watch
for select
to authenticated
using (
  exists (
    select 1
    from public.users
    where users.id = auth.uid()
      and users.role = 'admin'
      and users.status = 'active'
  )
);


-- =========================================================
-- 8. Realtime
-- =========================================================

alter table public.analytics_sessions replica identity full;

alter table public.analytics_events replica identity full;


-- =========================================================
-- 9. Add tables to Realtime publication
-- =========================================================

do $$
begin

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'analytics_sessions'
  ) then

    alter publication supabase_realtime
    add table public.analytics_sessions;

  end if;


  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'analytics_events'
  ) then

    alter publication supabase_realtime
    add table public.analytics_events;

  end if;

end $$;